version: '1.0'
services:
  db_dev:
    container_name: db_dev
    image: postgres
    restart: ${restart}
    environment:
      POSTGRES_USER: ${postgres_user_dev}
      POSTGRES_PASSWORD: ${postgres_password_dev}
      POSTGRES_DB: ${postgres_db_name_dev}
    networks:
      default:
      traefik_gateway:

  pgadmin_dev:
    container_name: pgadmin_dev
    depends_on: 
      - db_dev
    image: dpage/pgadmin4
    restart: ${restart}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${pgadmin_user_dev}
      PGADMIN_DEFAULT_PASSWORD: ${pgadmin_password_dev}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin_dev.tls=true"
      - "traefik.http.routers.pgadmin_dev.entrypoints=websecure"
      - "traefik.http.routers.pgadmin_dev.rule=Host(`dev.pgadmin.${base_url}`)"
      - "traefik.http.services.pgadmin_dev.loadbalancer.server.port=80"
    networks:
      default:
      traefik_gateway:

  db_lrs_dev:
    image: postgres
    container_name: db_lrs_dev
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${lrs_postgres_user_dev}
      POSTGRES_PASSWORD: ${lrs_postgres_password_dev}
      POSTGRES_DB: ${lrs_postgres_db_name_dev}
    restart: ${restart}
    networks:
      default:
      traefik_gateway:

  lrs_dev:
    image: yetanalytics/lrsql:${lrs_tag}
    container_name: lrs_dev
    command:
      - /lrsql/bin/run_postgres.sh
    depends_on:
      - db_lrs_dev
    environment:
      LRSQL_API_KEY_DEFAULT: ${lrs_key_dev}
      LRSQL_API_SECRET_DEFAULT: ${lrs_secrect_dev}
      LRSQL_ADMIN_USER_DEFAULT: ${lrs_username_dev}
      LRSQL_ADMIN_PASS_DEFAULT: ${lrs_password_dev}
      LRSQL_DB_HOST: db_lrs_dev
      LRSQL_DB_NAME: ${lrs_postgres_db_name_dev}
      LRSQL_DB_USER: ${lrs_postgres_user_dev}
      LRSQL_DB_PASSWORD: ${lrs_postgres_password_dev}
      LRSQL_ALLOW_ALL_ORIGINS : true
      LRSQL_POOL_INITIALIZATION_FAIL_TIMEOUT: 10000
    restart: ${restart}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lrs_dev.rule=Host(`dev.lrs.${base_url}`)"
      - "traefik.http.routers.lrs_dev.tls=true"
      - "traefik.http.services.lrs_dev.loadbalancer.server.port=8080"
    networks:
      default:
      traefik_gateway:

  backend_dev:
    image: ghcr.io/haski-rak/haski-backend:${backend_tag}
    container_name: backend_dev
    depends_on:
      - pgadmin_dev
      - lrs_dev
    env_file:
      - ${env_file_backend_dev}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.haski_backend_dev.rule=Host(`dev.haski.${base_url}`)"
      - "traefik.http.routers.haski_backend_dev.tls=true"
      - "traefik.http.services.haski_backend_dev.loadbalancer.server.port=5000"
    restart: ${restart}
    networks:
      default:
      traefik_gateway:

  frontend_dev:
    image: ghcr.io/haski-rak/haski-frontend-frontend:${frontend_tag}
    depends_on:
      - backend_dev
    command:
      - "nginx"
      - "-g"
      - "daemon off;"
    env_file:
      - ${env_file_frontend_dev}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.haski_frontend_dev.tls=true"
      - "traefik.http.routers.haski_frontend_dev.entrypoints=websecure"
      - "traefik.http.routers.haski_frontend_dev.rule=Host(`${base_url}`)"
      - "traefik.http.services.haski_frontend_dev.loadbalancer.server.port=80"
    restart: ${restart}
    networks:
      default:
      traefik_gateway:

  maria_db_dev:
    image: docker.io/bitnami/mariadb:${maria_db_tag}
    container_name: maria_db_dev
    environment:
      - MARIADB_USER=${maria_db_user_dev}
      - MARIADB_PASSWORD=${maria_db_password_dev}
      - MARIADB_DATABASE=${maria_db_database_dev}
      - MARIADB_ROOT_PASSWORD=${maria_db_root_password_dev}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data_dev:/bitnami/mariadb'
    restart: ${restart}

  moodle_dev:
    image: docker.io/bitnami/moodle:${moodle_tag}
    container_name: moodle_dev
    depends_on:
      - maria_db_dev
    environment:
      - MOODLE_DATABASE_HOST=maria_db_dev
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=${maria_db_user_dev}
      - MOODLE_DATABASE_PASSWORD=${maria_db_password_dev}
      - MOODLE_DATABASE_NAME=${maria_db_database_dev}
    volumes:
      - 'moodle_data_dev:/bitnami/moodle'
      - 'moodledata_data_dev:/bitnami/moodledata'
    restart: ${restart}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moodle_dev.rule=Host(`dev.moodle.${base_url}`)"
      - "traefik.http.routers.moodle_dev.tls=true"
    networks:
      default:
      traefik_gateway:

  phpmyadmin_dev:
    image: phpmyadmin
    container_name: phpmyadmin_dev
    restart: ${restart}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin_dev.rule=Host(`dev.db.moodle.${base_url}`)"
      - "traefik.http.routers.phpmyadmin_dev.tls=true"
    environment:
      - PMA_ARBITRARY=1

networks:
  default:
  traefik_gateway:
    name: traefik_gateway
    external: true
    
volumes:
  mariadb_data_dev:
    driver: local
  moodle_data_dev:
    driver: local
  moodledata_data_dev:
    driver: local
