version: '1.0'
services:
  db_prod:
    container_name: db_prod
    image: postgres
    restart: ${restart}
    environment:
      POSTGRES_USER: ${postgres_user_prod}
      POSTGRES_PASSWORD: ${postgres_password_prod}
      POSTGRES_DB: ${postgres_db_name_prod}
    networks:
      default:
      traefik_gateway:

  pgadmin_prod:
    container_name: pgadmin_prod
    depends_on: 
      - db_prod
    image: dpage/pgadmin4
    restart: ${restart}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${pgadmin_user_prod}
      PGADMIN_DEFAULT_PASSWORD: ${pgadmin_password_prod}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin_prod.tls=true"
      - "traefik.http.routers.pgadmin_prod.entrypoints=websecure"
      - "traefik.http.routers.pgadmin_prod.rule=Host(`pgadmin.${base_url}`)"
      - "traefik.http.services.pgadmin_prod.loadbalancer.server.port=80"
    networks:
      default:
      traefik_gateway:

  db_lrs_prod:
    image: postgres
    container_name: db_lrs_prod
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${lrs_postgres_user_prod}
      POSTGRES_PASSWORD: ${lrs_postgres_password_prod}
      POSTGRES_DB: ${lrs_postgres_db_name_prod}
    restart: ${restart}
    networks:
      default:
      traefik_gateway:

  lrs_prod:
    image: yetanalytics/lrsql:${lrs_tag}
    container_name: lrs_prod
    command:
      - /lrsql/bin/run_postgres.sh
    depends_on:
      - db_lrs_prod
    environment:
      LRSQL_API_KEY_DEFAULT: ${lrs_key_prod}
      LRSQL_API_SECRET_DEFAULT: ${lrs_secrect_prod}
      LRSQL_ADMIN_USER_DEFAULT: ${lrs_username_prod}
      LRSQL_ADMIN_PASS_DEFAULT: ${lrs_password_prod}
      LRSQL_DB_HOST: db_lrs_prod
      LRSQL_DB_NAME: ${lrs_postgres_db_name_prod}
      LRSQL_DB_USER: ${lrs_postgres_user_prod}
      LRSQL_DB_PASSWORD: ${lrs_postgres_password_prod}
      LRSQL_ALLOW_ALL_ORIGINS : true
      LRSQL_POOL_INITIALIZATION_FAIL_TIMEOUT: 10000
    restart: ${restart}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lrs_prod.rule=Host(`lrs.${base_url}`)"
      - "traefik.http.routers.lrs_prod.tls=true"
      - "traefik.http.services.lrs_prod.loadbalancer.server.port=8080"
    networks:
      default:
      traefik_gateway:

  backend_prod:
    image: ghcr.io/haski-rak/haski-backend:${backend_tag}
    container_name: backend_prod
    depends_on:
      - pgadmin_prod
      - lrs_prod
    env_file:
      - ${env_file_backend_prod}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.haski_backend_prod.rule=Host(`haski.${base_url}`)"
      - "traefik.http.routers.haski_backend_prod.tls=true"
      - "traefik.http.services.haski_backend_prod.loadbalancer.server.port=5000"
    restart: ${restart}
    networks:
      default:
      traefik_gateway:

  frontend_prod:
    image: ghcr.io/haski-rak/haski-frontend-frontend:${frontend_tag}
    depends_on:
      - backend_prod
    command:
      - "nginx"
      - "-g"
      - "daemon off;"
    env_file:
      - ${env_file_frontend_prod}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.haski_frontend_prod.tls=true"
      - "traefik.http.routers.haski_frontend_prod.entrypoints=websecure"
      - "traefik.http.routers.haski_frontend_prod.rule=Host(`${base_url}`)"
      - "traefik.http.services.haski_frontend_prod.loadbalancer.server.port=80"
    restart: ${restart}
    networks:
      default:
      traefik_gateway:

  maria_db_prod:
    image: docker.io/bitnami/mariadb:${maria_db_tag}
    container_name: maria_db_prod
    environment:
      - MARIADB_USER=${maria_db_user_prod}
      - MARIADB_PASSWORD=${maria_db_password_prod}
      - MARIADB_DATABASE=${maria_db_database_prod}
      - MARIADB_ROOT_PASSWORD=${maria_db_root_password_prod}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data_prod:/bitnami/mariadb'
    restart: ${restart}

  moodle_prod:
    image: docker.io/bitnami/moodle:${moodle_tag}
    container_name: moodle_prod
    depends_on:
      - maria_db_prod
    environment:
      - MOODLE_DATABASE_HOST=maria_db_prod
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=${maria_db_user_prod}
      - MOODLE_DATABASE_PASSWORD=${maria_db_password_prod}
      - MOODLE_DATABASE_NAME=${maria_db_database_prod}
    volumes:
      - 'moodle_data_prod:/bitnami/moodle'
      - 'moodledata_data_prod:/bitnami/moodledata'
    restart: ${restart}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moodle_prod.rule=Host(`moodle.${base_url}`)"
      - "traefik.http.routers.moodle_prod.tls=true"
    networks:
      default:
      traefik_gateway:

  phpmyadmin_prod:
    image: phpmyadmin
    container_name: phpmyadmin_prod
    restart: ${restart}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin_prod.rule=Host(`db.moodle.${base_url}`)"
      - "traefik.http.routers.phpmyadmin_prod.tls=true"
    environment:
      - PMA_ARBITRARY=1

networks:
  default:
  traefik_gateway:
    name: traefik_gateway
    external: true
    
volumes:
  mariadb_data_prod:
    driver: local
  moodle_data_prod:
    driver: local
  moodledata_data_prod:
    driver: local
